[2024-06-16T14:30:07.962+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: weather_pipeline.extract_weather_data manual__2024-06-16T12:38:57.714784+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
