[2024-06-16T14:13:25.406+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: weather_pipeline.extract_weather_data scheduled__2024-05-19T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
